version: '3.8'
services:
  schrodingers-whale:
    image: schrodingers-whale:latest
    container_name: schrodingers-whale
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "quantum.state=superposition"